version: "3.8"
services:
  react-docker-victory:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #  - ./.env
